### ISSUE TITLE
"location" and "description" fields are set to "" instead of null

### ISSUE THREAD

**Issue by rfc2822** [dmfs/opentasks#168]
When creating a new task without location and description, the Content Provider returns `""` instead of `null` for those values (tasks.db contains `""`, too).

For other fields like url and geo, it works as expected – when no URL and no geo position is entered, the fields are `null`.

So I guess it would be better to set those field values to `null`, too, if there's no content.

**Comment by dmfs** [comment]
I think that's debatable. Technically, that's what the user has entered, an empty string. You can not enter a `null` string (that would only be the case if we allow to remove these fields from the UI, i.e. so the field doesn't exist).
That's quite different from the URL field. If the user didn't enter a URL, we store `null` because there is no URL (by definition, there is no such thing as an "empty URL").
The key difference is that location and description are string values, which can be empty, but geo and URL are structured values which either exist or not, but which can not be empty.

I don't mind storing `null` for empty strings, but it doesn't feel quite right. IMHO it's up to the sync layer to determine if empty strings need to be transferred or if they can be omitted. There might be task sync protocols, that require description to be present and non-`null`. Also you still have to deal with tasks coming from the server having an empty description or location field. There is nothing in RFC 5545 that says empty location or description properties are not allowed.

**Comment by rfc2822** [comment]
I'm not convinced that when a user doesn't enter location and description, the entered record (= what's written to the tasks provider) should be:

* location set, it's `""`
* description set, it's `""`

But it's of course your decision – I'll do a [stripToNull](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/StringUtils.html#stripToNull%28java.lang.String%29) on those fields, it won't hurt.

> There is nothing in RFC 5545 that says empty location or description properties are not allowed.

No, but in my opinion, an empty location property has not the same meaning as no location property.
