### ISSUE TITLE
Provide sharing to Android Feature 

### ISSUE THREAD

**Issue by maulwuff** [dmfs/opentasks#172]
Add Feature to share tasks with other Android apps (i. e. Email, Threema,  ES File Manager)

**Comment by dmfs** [comment]
@lemonboston please take care of this. The share option should appear in the menu of the task detail view.
The share option should share a text document that contains all the details.

**Comment by lemonboston** [comment]
@dmfs ok, just to confirm, the text document here will be just an easy to read, custom (non-standard) format not an `.ics` (iCalendar - VTODO) file, right? Thanks.

**Comment by lemonboston** [comment]
I wanted to print all available data for a task, so using the code below from `ViewTaskFragment`:
```
List<FieldDescriptor> fields = model.getFields();
// iter over fields:
Object o = field.getFieldAdapter().get(contentSet);
sb.append(field.getTitle()).append(": ").append(o.toString()).append("\n");
```
I got this output for a local task for which I filled out every field in the Edit task screen:
```
List: -15108409
List: My tasks
List: Local
Title: task title
Status: 2
Location: locationtext
Description: desc
Check list: [org.dmfs.tasks.model.CheckListItem@3d10ff95, org.dmfs.tasks.model.CheckListItem@37b24e02]
Start: 20160923T171500Europe/Budapest(5,266,7200,1,1474643700)
Due: 20160928T140500Europe/Budapest(3,271,7200,1,1475064300)
All Day: false
Time Zone: libcore.util.ZoneInfo[id="Europe/Budapest",mRawOffset=3600000,mEarliestRawOffset=3600000,mUseDst=true,mDstSavings=3600000,transitions=152]
Completed: 20160930T190000UTC(5,273,0,0,1475262000)
Percent complete: 100
Priority: 5
Privacy: 2
URL: http://someurl.com
List: My tasks (Local)
```
So I assume this is all the available data to include in the shared text. (?)

Below is a first proposal how we could format it for the shared text. _List_, _Status_, and _Percent complete_ fields are not added. (If any property is not present, that line won't be added.)
@dmfs Please let me know if something like this would be okay.

```
Task from OpenTasks:

Title: <task title>
Description: <task description>
Check list:
 - <checked/unchecked with special char?> <check list item 1> 
 - <checked/unchecked with special char?> <check list item 2> 
Location: <task location>
Start: <start date time>
Due: <due date time>
Completed: <completed date time>
Time Zone: <time zone>
Priority: <priority text>
Privacy: <privacy text>
URL: <url>
```

**Comment by dmfs** [comment]
I don't think that we need the labels for all of the items. In some cases it's pretty clear what it means. Also The title doesn't need to be "Task from OpenTask". IIRC the share intent has a "title" extra. That should be the title of the task. As for the content I think we could do something like this.

```
<task title>
============

<task description>
[X] checked list item
[ ] unchecked list item

Start: <start date time> <timezone>
Due: <due date time> <timezone>
Completed: <due date time> <timezone>
Priority: <priority text>
Privacy: <privacy text> 
<url>

Shared by OpenTasks
```
Of course, if a field is missing the entire line should be omitted.

Ideally we can make it compatible to Google Keep. As it happens OpenTasks can understand the notes and checklists shared by Google Keep (by coincidence they use the same format for the check list items). Not sure about the due dates though.

Ideally we use some sort of template that we can localize.

**Comment by korelstar** [comment]
Why don't you use iCalendar format/type or let the user choice which format to use (plain text or iCalendar)? It would also be useful to share single tasks in iCalendar format to other people, who could import the task directly into their task list.

**Comment by dmfs** [comment]
@korelstar maybe later. I think it's reasonable to start with a simple option. We surely can improve it later on.
Also, I think that it's probably better to add participants instead (which is similar to attendees for calendars). Adding participants will make sure that they will get updates when we modify a task (we can't do that when sharing it in an email, because the recipient will be unknown to OpenTasks).

**Comment by korelstar** [comment]
Okay

**Comment by lemonboston** [comment]
A few questions about implementation:

- Should we force app chooser or not upon sharing? ([docs1](https://developer.android.com/training/basics/intents/sending.html#AppChooser), [docs2](https://developer.android.com/guide/components/intents-filters.html#ForceChooser) - they suggest forcing chooser for sharing). 
If we don't force then the first time all apps are shown, the 2nd time the last time selected one is brought up and choice offered to select it as always, which would result that next time that app opens automatically without question. This can only be reset in device settings.
If we force chooser, all apps (and contacts) are shown always without highlighting the last one, so user always have to find the app in the list, which might need scrolling.
- Should the task title be part of the body or not?
We can send the texts as EXTRA_TEXT and EXTRA_SUBJECT in the Intent. If it is received by an email app, it will be the email body and subject respectively. Also, Google Keep will use EXTRA_SUBJECT as the task title and EXTRA_TEXT as the content. So it is fine, but if the receiving app wants to save the text as a file, for example I tried it with Total Commander, then only EXTRA_TEXT will be used for the content of the file, so we could loose task title.

With title in the EXTRA_TEXT as well:
![double-title](https://cloud.githubusercontent.com/assets/1077972/18951865/9727816e-8647-11e6-9594-87a0f0656c51.png)
- I would like to just double-check if _status_ (needs action/in process/done/cancelled/incomplete) would really be needed. I ask it partly because it is the only property that gets added by default. So even if the task only had title and we share it, the line "Status: needs action" is added. The other reason why I ask it is because if I imagine sharing a task, I think the status of it would probably not be relevant. It is a changing property and if I share a task, it probably means that it has to be completed or I want to share/save some information. But I probably don't do it as a way to create a snapshot of the status of the task. I might be wrong, I am not actually a user, so I am not sure.
What do you think, add status or not?

Thanks.

**Comment by dmfs** [comment]
Yes, we should force an app chooser. We can not assume that users always want to use share with the same app (and it's annoying to have to go to the settings and to reset the defaults if you hit the wrong button).
However, some apps show two share options, a generic one and another one for the last app that was selected (in which case no chooser is shown). Not sure how that feature is called and if there is a support utility for that.
In addition it might be useful to show our own app chooser. That way we could let the user select the app before we build the intent. If we know the target app before we build the share intent we can build a more adequate share intent. That way we could omit the title when sharing with Google keep or a known email app. Later on we could share it as an IMIP message when sharing with a known email app or share it as HTML if we know the target supports it.
For now we add the title to the document as well.

Yes, I want the status in there. It could be sufficient to add the progress, but not all task models have a progress. The only case in which we probably can omit the status is when the task has been completed (because we have the completed date in there).

It also occurred to me that we probably should be able to parse the format that we share. What do you think?

**Comment by dmfs** [comment]
@lemonboston  We don't use Google Translate for translations. For now we keep the English version, you can do the Hungarian and I do the German translation.

**Comment by dmfs** [comment]
In terms of architecture, I'd prefer something like this:

```
public final class SharedTaskText implements CharSequence {
  ...
}
```

That's applied like so
```
CharSequence sharedText = new SharedTaskText(contentSet);
```
I.e. using an adapter pattern that adapts the task to a CharSequence (which can be converted to a String using `toString()`).
In general I'd prefer this more "declarative" approach.

**Comment by lemonboston** [comment]
Thanks for the clarifications and input.

> The only case in which we probably can omit the status is when the task has been completed (because we have the completed date in there).

I've updated code to omit status for completed task.

> @lemonboston We don't use Google Translate for translations. For now we keep the English version, you can do the Hungarian and I do the German translation.

Okay, if you let me know the German ones, I will update:
```
<string name="activity_task_details_share">Share</string> // menu item short name
<string name="activity_task_details_share_task">Share task</string> // menu item long name
<string name="share_footer">Shared by OpenTasks</string>
```
For the Hungarian one, could you please check if it has been merged to staging? [I couldn't find it](https://github.com/dmfs/opentasks/pull/245#issuecomment-250219791).

---
Regarding parsing the format we share, yes, I think you are right, it probably makes sense that if OpenTasks receive the same text shared that it created than it could parse it back to a task.
I don't know how often this would be used, but I assume much rarely compared to sharing, maybe like 10 to 1, so I think it would make sense to treat it as a separate feature and complete this one first. But of course it's worth thinking forward about implementation now, to see if it could affect text format or anything else.

I don't have much experience with templates, parsing, but I looked up template engines libraries a little bit now to see if they can parse as well, but it looks like they can't (I guess that is not a straightforward problem). So I assume now that regardless of how we generate the format, we will probably need a separate solution for parsing. Perhaps regular expressions for each field and some logic (a lib [here](https://github.com/sonalake/utah-parser), although we would be probably better off writing our own custom logic). Assessing whether a shared text is actually in our format or not might be the trickier part: checking for the footer might not be enough, cause user could delete that, so probably checking for our title format as well. Not sure if we should change anything in the format to make parsing easier. Any ideas, suggestions?
I think this is probably the only thing we need to do at this point, to make sure the format is parseable theoretically. (Note: I suppose we will only be able to parse texts that are in the actual language used.)
What do you think?

---

Regarding the adapter pattern and declarative style for representing the texts, I've implemented it on a separate branch ([172-share-task-declarative-text)](https://github.com/dmfs/opentasks/blob/issues/172-share-task-declarative-text/opentasks/src/main/java/org/dmfs/tasks/share/ShareTaskText.java), please check it out.

However, for me it doesn't seem to add anything in this case, because we right away call toString() on them:
So it changed from this:
```
String title = mTextComposer.title(contentSet, model);
String body = mTextComposer.body(contentSet, model);
```
to this:
```
String title = new TitleText(contentSet).toString();
String body = new ShareTaskText(contentSet, model, mActivity).toString();
```
So it's the same thing as someone noted for yegor's [Max object example](http://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html) (unfortunately that very good comment disappeared*), that we would only create this transient object just to immediately calculate a value with it. ("..it represents a continuation that you'll most likely immediately discard").
And even if we didn't discard the object immediately, then I would have concern that the captured context (ContentSet, Context) would live on, risking leaking.

So I would go with the 'function' way in this case, let me know how you would prefer.

*I had it saved in an email:
> Depending on what kind of a problem you are modeling, certain parts of code are better to express using OO paradigm, others using functions and function composition. They should be used when most appropriate.
Creating a new class just to express a pair of numbers that you can take a maximum of makes sense if these two numbers are always operated on as a pair and/or if the object will have an intransient existence. More often than not, though, you'll be taking these numbers individually from various sources and creating the Max object only to calculate its value. Such object is a functor; it represents a continuation that you'll most likely immediately discard. It seems like gratuitous obfuscation if you ask me.

**Comment by lemonboston** [comment]
App chooser is forced now, the title for the chooser is "Share task" now, the same string as for the menu item.
It would be possible to use a much longer text there (screen wide in normal text font), like "Share task as text" or "Share task <title> details as text", if needed.

**Comment by korelstar** [comment]
> Should we force app chooser or not upon sharing?

Did you have a look on the ShareActionProvider? I think that is state of the art for sharing in Android.

See https://developer.android.com/training/sharing/shareaction.html

**Comment by dmfs** [comment]
@korelstar That's what I meant. Unfortunately it only works by providing the share Intent upfront. AFAIK it doesn't allow to build an intent that's specific to the target.
Anyway, it's good enough for now.
@lemonboston, please use the ShareActionProvider.

**Comment by lemonboston** [comment]
I saw that in the docs with this note, so I didn't look into: 
> Note:  ShareActionProvider is available starting with API Level 14 and higher.

But I see that there is a v7 support library version, so I will check it out. Thanks.

**Comment by lemonboston** [comment]
Added `ShareActionProvider`, and it's much nicer with that:

![shareactionprovider](https://cloud.githubusercontent.com/assets/1077972/19034968/f450d6ac-8966-11e6-94c1-24d78865c039.png)
It lists the last used app first, so it's quite user friendly.
(Code on PR #277)

Unfortunately it is not possible to detect which app the user selects as you suspected @dmfs.

So currently the title is added to the body, too.

An alternative could be to add 2 submenus to the share menu item, like : _"...as title and body"_ and _"..as one text"_, or maybe add settings to the app so user can change the default behavior.
Video on how the submenu would look like (on Android 6.0.1): [link](https://drive.google.com/open?id=0Bzp0PP6UbK4lb055MG9Na3lyNGM)
What do you think?

**Comment by lemonboston** [comment]
@dmfs Could you please provide the German transations for these new strings?

```xml
    <string name="opentasks_task_details_menu_send_short">Send</string>
    <string name="opentasks_task_details_menu_send">Send to</string>
```
Both are for the menu item label (the short one is not used normally).

**Comment by lemonboston** [comment]
Oh, and this one, too:

```xml
    <!-- Outgoing share -->
    <string name="opentasks_share_footer">Shared by OpenTasks</string>
```
(The footer of the shared text message)

**Comment by dmfs** [comment]
```xml
    <string name="opentasks_task_details_menu_send_short">Teilen</string>
    <string name="opentasks_task_details_menu_send">Aufgabe teilen</string>
    <string name="opentasks_share_footer">Geteilt mit OpenTasks</string>
```

**Comment by lemonboston** [comment]
@dmfs Thanks, there is one more missing DE translation from earlier:
```
<string name="opentasks_details_no_task_selected">No task selected</string>
```
It is displayed in the middle of the empty details view fragment.

**Comment by dmfs** [comment]
```
<string name="opentasks_details_no_task_selected">Keine Aufgabe ausgewählt</string>
```

**Comment by dmfs** [comment]
merged

**Comment by dmfs** [comment]
ah, now quite but almost. Still need to rebase and resolve conflicts.
