### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by YSmhXQDd6Z** [dmfs/opentasks#187]
Please update the F-Droid version, the current version on F-Droid is 1.1.6. It would be nice if you upload the apk files here on GitHub too. Thanks

**Comment by dmfs** [comment]
I guess the folks at F-Droid wait for us to publish #133. We're working of the remaining issue of v1.1.8 and we'll publish the new version soon.
Btw, we do have uploaded all apks to GitHub. Check out the releases folder. However, these releases are signed with our key, so you won't be able to install it over the F-Droid build (since that's signed with the F-Droid key).
