### ISSUE TITLE
Task description line feeds get destroyed when added with firefox or webinterface in windows.

### ISSUE THREAD

**Issue by quantumtechnology** [dmfs/opentasks#227]
If task descriptions are added by firefox or webinterface under windows, then
the line feeds are getting replaced by "\N" such that the folling:
abcdef
gijklm
nopq

gets replaced by
abcdef\Ngijklm\Nnopq

I guess this is an issue with the different line feeds in windows and linux environment.

**Comment by dmfs** [comment]
It would be interesting to see the original iCalendar data. Can you get that from your server?
In any case this doesn't look like an OpenTasks issue.

I suspect that the sync app doesn't recognize `\N` as valid new line sequence. According to [RFC 5545, section 3.3.11](https://tools.ietf.org/html/rfc5545#section-3.3.11) it actually is a valid new line escape sequence (just like `\n`). I've just checked CalDAV-Sync and I'm pretty sure we handle this correctly.

Another option would be that either the web UI or the server apply some invalid double escaping (i.e. `\\N` instead of `\N`), but I can't tell without having seen the original data.

**Comment by quantumtechnology** [comment]
I realized that it is an issue of the Caldav provider. On other systems this does not occur.
