### ISSUE TITLE
Drop Android 2.x and 3.x support.

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#392]
Market shares of Android 2.x and 3.x are close to zero. So it's hard to justify continued support and efforts for these Android versions.

This issue is about removing all workarounds we had to introduce for these versions as well as obsolete styles.

**Comment by lemonboston** [comment]
When this is implemented, make sure to look through all AndroidManifests in the project for
```
<uses-sdk tools:overrideLibrary=...>
```
usage, since those have been added because the used library had higher `minSdkVersion`. So those can possibly be removed at that time.

**Comment by dmfs** [comment]
@lemonboston The new `minSdkLevel` is `15`. You don't need to spend much time on removing all the workarounds for Android 2 and 3. Maybe just remove a few big annoying ones. We'll take care of the others whenever we stumble across them.

**Comment by lemonboston** [comment]
@dmfs Could we abandon API 15 - Android 4.0 - Ice Cream Sandwich as well?
According to the official Dashboard, it has only 0.5% share:
https://developer.android.com/about/dashboards/index.html

Since 4.1 Jelly Bean was a major, annual version update after 4.0, I suppose there are framework APIs that changed that time, and we could potentially remove some related backward compatible code for that as well.
https://en.wikipedia.org/wiki/Android_version_history (4.0: October 18, 2011, 4.1: July 9, 2012)

**Comment by dmfs** [comment]
We won't drop support for 15 atm. I can't remember any limitations or workarounds we had to add to support API level 15.
If you come across any, please open an issue.

**Comment by lemonboston** [comment]
Ok.
