### ISSUE TITLE
GET_ACCOUNTS runtime permission handling

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#407]
https://github.com/dmfs/opentasks/issues/404#issuecomment-323271866 :

> @lemonboston the app should check for the GET_ACCOUNTS permission on every start. If the permission has been granted it should continue, otherwise it should show a message about this issue and a "Grant" button which then launches the permission request. If the permission has been denied with "don't ask again" the message should instruct the user to go to settings and grant the permission.
> 
> Also check if we're using other runtime permissions.

**Comment by lemonboston** [comment]
Besides GET_ACCOUNTS the only other dangerous permission I see in the manifest is READ_CONTACTS. They both belong to the CONTACT group so once the user grants that, both will be granted.
But documentation say we shouldn't depend on these groups, so is the READ_CONTACTS permission needed to be checked on every start as well or is there a more specific place for that?

---

Just to have a better picture, where are these permissions used in the code? I mean that there is usually a lint error when trying to use an Android API which requires dangerous permission but we don't have that error, so is it because `ContentProvider` and/or `AccountManager` are too general to detect this?

---

I suppose `BaseActivity` `onCreate()` can be an obvious place to put this check. That is only introduced in this not yet merged pull request: https://github.com/dmfs/opentasks/pull/388
I will start to work on top of that, but if that doesn't make it to master, I can rebase of course and place the code in current Activities.

**Comment by dmfs** [comment]
We don't use READ_CONTACTS yet. We've already added this permission in advance for future features (like task delegation). So at present there is no need to request it.
The code which uses `GET_ACCOUNTS` is in OpenTasksProvider (and only there). It's quite possible that there is no lint error, because the function we use still works without this permission. It just has a different behavior (it only returns accounts which are owned by the app instead of all accounts).

**Comment by dmfs** [comment]
Released in 1.1.10
