### ISSUE TITLE
How do I create a synchronized task list?

### ISSUE THREAD

**Issue by kozross** [dmfs/opentasks#608]
I have a working CalDav via DavDroid, but every time I try to create a task list, I only get the option to make a local one (which the app says won't be synched). How do I make a task list that will be?

**Comment by anna6** [comment]
Do you have any progress since your posting? I can't also create a remote tasklist.

I have ownCloud on my NAS, Kontact on my Kubuntu Desktop and Etar calendar on my Android 6 phone (sync with DAVdroid).

If I create a calendar & Tasklist with DAVdroid it's shown in ownCloud (NAS), Kontact (PC) and Etar (Android 6) as _unnamed_ after I used _Identify calendar_ in DAVdroid, in OpenTasks no list is shown (_visible lists_, _synced lists_). If I create a Calendar with ownCloud, it's shown with it's name in ownCloud (NAS), Kontact (PC), DAVdroid and Etar (Android 6) but also not in OpenTasks. I can also create dates and tasks which are synced. OpenTasks shows nothing.

That's really strange, because I have one synced tasklist in OpenTasks, which works fine for month now (unfortunately I forgot how I created it).

**Comment by kozross** [comment]
The solution appears to be 'install OpenTasks before DAVDroid'. I've since documented this on my blog.
