### ISSUE TITLE
Feature Request: Reorder checklist by drag/drop

### ISSUE THREAD

**Issue by maulwuff** [dmfs/opentasks#75]
It would be a nice feature to reoder a checklist styled task by drag/drop

**Comment by Ezelty** [comment]
I know this issue is quite old, but I would really like to be able to reorder my items! If it's too complicated to add a drag/drop system, could you add an option to sort the items alphabetically? Or an option to set some items as more important, and put them on the top of the checklist? I often put a star or an emoji at the beginning of some items to see which items are important and create sort of categories, so having my items sorted alphabetically would be very useful to me,as it would gather the items with a star or with the same emoji. :)

**Comment by dmfs** [comment]
Drag and drop shouldn't be too difficult. We just had to make some internal changes to make this work. The latest release already contains these internal improvements, so now it's "just" the UI that needs some work.

**Comment by dmfs** [comment]
We've just finished the implementation of this and are currently testing it. Send us an email if you want to test the pre-release of the app.

**Comment by maulwuff** [comment]
Gern
