### ISSUE TITLE
Recurring tasks bug

### ISSUE THREAD

**Issue by Lykos153** [dmfs/opentasks#81]
> When completing a repeating task from davical server (connected
> using caldav-sync), the task no longer repeats.

**Comment by tannyl** [comment]
Hey Marten. :)

I also run into this problem or a similar problem. I know recurring tasks are not supported, but the "the entire series should be set to complete" is not happening, or at least not on my setup.

I run a Baikal CalDav and CardDav server.
On my PC I use Rainlendar to manage tasks and events, which supports recurring tasks just fine.
And on my Android phone I of course use your applications.

Here is what happens:

1: In Rainlendar I made a test task and set it to repeat every day.
2: Ones synced to the phone I waited for it to show up in the notifications list.
3: I completed the task on the phone. As expected it disappeared from the phones task list.
4: Now the interesting part is ones Rainlendar synced with the CalDav server, the task was still there, but now showing up as a task for tomorrow. I completed that task as well, and it then showed up as a task for the next day again.
5: I tried to sync the phone again, but sadly the task does not show up again.

I guess a reason for this could be that your Task app sets the entire task as completed, but Rainlendar ignores this and only checks the date of the latest completed recurring task, which you do not change (I haven't looked at how this info is actually stored in the cal files.)

I would really love to see the recurring tasks keep showing up in Tasks just as they do in Rainlendar. So here is a suggestion:
I know full recurring task support ain't coming just yet, but what about a small 'fix'. If your Task app sees that a task is a recurring task, then instead of completing the whole task, it just "completes to now".? This would be super useful, and actually this is the reason I don't really use your Tasks app yet. :-(

If you want the task data, just let me know and I'll get it for you.

**Comment by dmfs** [comment]
Hi tannyl, that's basically what we're working on. I guess Rainlendar tries to be smart about the completion state. We're planning to implement something similar.
The major reason why we didn't finish the implementation yet is the lack of support for certain aspects of the standard on Apple devices. However, we need to ensure our implementation complies with their implementation, because Apple users have a huge share in our user base.

**Comment by tannyl** [comment]
Its always those Apple guys holding us back. :-)

Thanks for the reply.. I hope we will see some work on the Task area soon.

Who might I bribe to speed up the process? ;-)

**Comment by ts78** [comment]
Any news on that? I did not see any development branch for an early preview or something like this, is there already a beta version available that supports recurring tasks? Otherwise I might also want to look into the code to add some support for it..

**Comment by dmfs** [comment]
We're working on that. We do have a development branch, but we don't publish any work in progress code. Also, we need to finish dmfs/opentask-provider#1 first, it wouldn't make sense the other way round.

**Comment by languitar** [comment]
:+1:

**Comment by dmfs** [comment]
This is now tracked under #462
