### ISSUE TITLE
[request] Change description

### ISSUE THREAD

**Issue by Valdnet** [dmfs/opentasks#920]
I suggest changing the description from "Synchronized Lists" to "Lists for synchronization" in "Displayed Lists".
In my opinion, this is more understandable to the user.

![obraz](https://user-images.githubusercontent.com/47037905/74742924-cc3ad580-525f-11ea-840a-749734a60a6f.png)

Exactly this description:
https://github.com/dmfs/opentasks/blob/57ab48bfe71f82ac7a5bc49e7b9633fbf0de2c9c/opentasks/src/main/res/values/strings.xml#L155

**Comment by dmfs** [comment]
The synchronized list view is probably going to be removed in future version. I think it's up to the sync app to provide this functionality. The "displayed lists" view is going to be replaced by a navigation drawer where you can show/hide individual lists (similar to how the Google calendar app uses it).
That's why I'd like to avoid putting much more effort into this activity. Same goes for #921 .

**Comment by Valdnet** [comment]
I think so too 😉. Thanks for the reply and I close the request.
