### ISSUE TITLE
OpenTasks doesn't ask for permissions on start

### ISSUE THREAD

**Issue by szotsaki** [dmfs/opentasks#927]
I have removed and then reinstalled OpenTasks on my device (Android 8.0.0). When I started the new instance it didn't have the permissions of "Contacts" and "Tasks" and therefore it was not possible to sync with DAVx5/DAVDroid until I granted them manually in Android settings.

Please, check and ask for the permissions when starting the program.

**Comment by dmfs** [comment]
There is no need to request the `Tasks` permission because OpenTasks is the owner and doesn't have to request it. It's always granted access to the tasks, even if you revoke the permission or do not grant it in the first place.

We have code in place to request the `Contacts` permission, see [BaseActivity, line 94](https://github.com/dmfs/opentasks/blob/master/opentasks/src/main/java/org/dmfs/tasks/utils/BaseActivity.java#L94). It's disabled for Android 8 and newer because Android 8 introduced another mechanism to solve the underlying problem (see #404, #596 and #728 for further information).

Note that currently we don't access contacts, we've been using this for the `GET_ACCOUNTS` part of the permission group.

I have no idea why syncing didn't work in your case until you granted these permissions. I don't think it's related to these though. On Android 8 and newer neither of these permissions is required for OpenTasks to work correctly.

**Comment by dmfs** [comment]
Here is what probably happened:
When you installed OpenTasks for the first time and set up the account in DavDroid, DavDroid has given OpenTasks access to the newly created account (i.e. made it visible to OpenTasks). By uninstalling OpenTasks this permission was revoked. When you reinstalled OpenTasks, the permission had to be granted again, otherwise OpenTasks would not see the account (and remove any list created by DavDroid for that account). I would assume that DavDroid eventually gave that permission again. Not sure when exactly this happens, but it's probably just been coincidentally around the time you granted these permissions to OpenTasks.
